/**
 * Contract ABIs for LUKSO Game Contracts
 * Auto-extracted from Foundry compilation output
 */

export const characterNFTAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "name_", type: "string" },
      { name: "symbol_", type: "string" },
      { name: "owner_", type: "address" },
      { name: "mintPrice_", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "fallback", stateMutability: "payable" },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "GRID_SIZE",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TOTAL_ROOMS",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "tokenOwner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "blockRegistry",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "characterToRoom",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "characters",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      { name: "characterType", type: "uint8" },
      { name: "name", type: "string" },
      { name: "imageUrl", type: "string" },
      {
        name: "room",
        type: "tuple",
        components: [
          { name: "x", type: "uint8" },
          { name: "y", type: "uint8" },
          { name: "z", type: "uint8" },
        ],
      },
      { name: "mintedAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAvailableRooms",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "x", type: "uint8" },
          { name: "y", type: "uint8" },
          { name: "z", type: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCharacter",
    inputs: [{ name: "tokenId", type: "bytes32" }],
    outputs: [
      { name: "characterType", type: "uint8" },
      { name: "name", type: "string" },
      { name: "imageUrl", type: "string" },
      { name: "roomX", type: "uint8" },
      { name: "roomY", type: "uint8" },
      { name: "roomZ", type: "uint8" },
      { name: "mintedAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCharacterInRoom",
    inputs: [
      { name: "x", type: "uint8" },
      { name: "y", type: "uint8" },
      { name: "z", type: "uint8" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoomForCharacter",
    inputs: [{ name: "tokenId", type: "bytes32" }],
    outputs: [
      { name: "x", type: "uint8" },
      { name: "y", type: "uint8" },
      { name: "z", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isRoomAvailable",
    inputs: [
      { name: "x", type: "uint8" },
      { name: "y", type: "uint8" },
      { name: "z", type: "uint8" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "characterType_", type: "uint8" },
      { name: "name_", type: "string" },
      { name: "imageUrl_", type: "string" },
      { name: "roomX", type: "uint8" },
      { name: "roomY", type: "uint8" },
      { name: "roomZ", type: "uint8" },
    ],
    outputs: [{ name: "tokenId", type: "bytes32" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "mintPrice",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "roomToCharacter",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenIdsOf",
    inputs: [{ name: "tokenOwner", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenOwnerOf",
    inputs: [{ name: "tokenId", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalMinted",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CharacterMinted",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "tokenId", type: "bytes32", indexed: true },
      { name: "characterType", type: "uint8", indexed: false },
      { name: "name", type: "string", indexed: false },
      { name: "roomX", type: "uint8", indexed: false },
      { name: "roomY", type: "uint8", indexed: false },
      { name: "roomZ", type: "uint8", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "operator", type: "address", indexed: false },
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "tokenId", type: "bytes32", indexed: true },
      { name: "force", type: "bool", indexed: false },
      { name: "data", type: "bytes", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "EmptyCharacterName",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientPayment",
    inputs: [
      { name: "required", type: "uint256" },
      { name: "provided", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InvalidCharacterType",
    inputs: [{ name: "typeId", type: "uint8" }],
  },
  {
    type: "error",
    name: "InvalidRoomCoordinates",
    inputs: [
      { name: "x", type: "uint8" },
      { name: "y", type: "uint8" },
      { name: "z", type: "uint8" },
    ],
  },
  {
    type: "error",
    name: "RoomAlreadyOccupied",
    inputs: [
      { name: "x", type: "uint8" },
      { name: "y", type: "uint8" },
      { name: "z", type: "uint8" },
    ],
  },
] as const;

export const blockTokenAbi = [
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "tokenOwner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "blockName",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockInfo",
    inputs: [],
    outputs: [
      { name: "name", type: "string" },
      { name: "premium", type: "bool" },
      { name: "price", type: "uint256" },
      { name: "path", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isPremium",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "modelPath",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "placeBlocks",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pricePerUnit",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchase",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "registry",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BlockPlaced",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlockPurchased",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalCost", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BlockRemoved",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InsufficientBlocks",
    inputs: [
      { name: "required", type: "uint256" },
      { name: "available", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientPayment",
    inputs: [
      { name: "required", type: "uint256" },
      { name: "provided", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "NotPremiumBlock",
    inputs: [],
  },
] as const;

export const blockTypeRegistryAbi = [
  {
    type: "function",
    name: "allBlockTypeIds",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "tokenOwner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "blockTypes",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "isPremium", type: "bool" },
      { name: "pricePerUnit", type: "uint256" },
      { name: "modelPath", type: "string" },
      { name: "tokenContract", type: "address" },
      { name: "exists", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "characterNFT",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllBlockTypes",
    inputs: [],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockContract",
    inputs: [{ name: "blockTypeId", type: "bytes32" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockTypeCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBlockTypeInfo",
    inputs: [{ name: "blockTypeId", type: "bytes32" }],
    outputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "isPremium", type: "bool" },
      { name: "pricePerUnit", type: "uint256" },
      { name: "modelPath", type: "string" },
      { name: "tokenContract", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "startingBlockQuantities",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "BlockTypeRegistered",
    inputs: [
      { name: "blockTypeId", type: "bytes32", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "isPremium", type: "bool", indexed: false },
      { name: "tokenContract", type: "address", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StartingBlocksGranted",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "characterTokenId", type: "bytes32", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "BlockTypeAlreadyExists",
    inputs: [{ name: "blockTypeId", type: "bytes32" }],
  },
  {
    type: "error",
    name: "BlockTypeNotFound",
    inputs: [{ name: "blockTypeId", type: "bytes32" }],
  },
] as const;

export const photoFrameBlockAbi = [
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "tokenOwner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "clearFrameMetadata",
    inputs: [{ name: "frameIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "frameMetadata",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    outputs: [
      { name: "imageUrl", type: "string" },
      { name: "linkUrl", type: "string" },
      { name: "description", type: "string" },
      { name: "isSet", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllFrameMetadata",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      { name: "indices", type: "uint256[]" },
      { name: "imageUrls", type: "string[]" },
      { name: "linkUrls", type: "string[]" },
      { name: "descriptions", type: "string[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFrameInfo",
    inputs: [],
    outputs: [
      { name: "price", type: "uint256" },
      { name: "path", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFrameMetadata",
    inputs: [
      { name: "owner", type: "address" },
      { name: "frameIndex", type: "uint256" },
    ],
    outputs: [
      { name: "imageUrl", type: "string" },
      { name: "linkUrl", type: "string" },
      { name: "description", type: "string" },
      { name: "isSet", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "metadataCount",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "modelPath",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "placeFrame",
    inputs: [{ name: "frameIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pricePerUnit",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "purchase",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "registry",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setFrameMetadata",
    inputs: [
      { name: "frameIndex", type: "uint256" },
      { name: "imageUrl", type: "string" },
      { name: "linkUrl", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "FrameMetadataCleared",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "frameIndex", type: "uint256", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FrameMetadataSet",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "frameIndex", type: "uint256", indexed: true },
      { name: "imageUrl", type: "string", indexed: false },
      { name: "linkUrl", type: "string", indexed: false },
      { name: "description", type: "string", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FramePlaced",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "frameIndex", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FramePurchased",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "totalCost", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FrameRemoved",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "frameIndex", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "FrameIndexOutOfBounds",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "balance", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientFrames",
    inputs: [
      { name: "required", type: "uint256" },
      { name: "available", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "InsufficientPayment",
    inputs: [
      { name: "required", type: "uint256" },
      { name: "provided", type: "uint256" },
    ],
  },
  {
    type: "error",
    name: "MetadataNotSet",
    inputs: [{ name: "frameIndex", type: "uint256" }],
  },
] as const;


